### ISSUE TITLE
Train dataset

### ISSUE THREAD

**Issue by charlesXu86** [facebookresearch/svoice#11]
How to get more train dataset?

**Comment by adiyoss** [comment]
You can get a pretty big dataset under the following link: https://github.com/JorisCos/LibriMix 
I highly recommend augment it with reverb using some room-impulse-response generator such as this one: https://github.com/LCAV/pyroomacoustics

**Comment by charlesXu86** [comment]
> You can get a pretty big dataset under the following link: https://github.com/JorisCos/LibriMix
> I highly recommend augment it with reverb using some room-impulse-response generator such as this one: https://github.com/LCAV/pyroomacoustics

thank you so much！

**Comment by adiyoss** [comment]
Closing this issue, if you have more questions, feel free to open another one or reopen this one!
