### ISSUE TITLE
How to consider noise added mixtures in training?

### ISSUE THREAD

**Issue by Turan111** [facebookresearch/svoice#16]
I am trying to train mix_both (utterances + noise) subset in Libri2mix dataset. Vocal utterances are from Librispeech dataset and noise wavs are from WHAM dataset. 
How should I consider added noise wavs? I mean take them as the third speaker s3 and train as 3mix model or just train 2mix model like mix_clean?

**Comment by adiyoss** [comment]
Hi @Turan111,
I think it depends on you task. Do you want to model the noise too or not? 
In our case, since we were only interested in the clean and separated signals, we simply ignored the noise and predicted the clean signals only. That way the model is both separating and denoising.

**Comment by Turan111** [comment]
Hi @adiyoss ,
Many thanks for the responce,
I don't want to model noise, but I am interested in the clean and separated human voice. In this case which approach gives better results? Have you done such experiment?

**Comment by adiyoss** [comment]
@Turan111
Yes, so we did experiment with training on noisy (w./wo. reverb) mixtures and predicting the clean separated channels. We experimented with WHAM! and WHAMR! benchmarks (http://wham.whisper.ai/).

**Comment by adiyoss** [comment]
Closing this issue for now. Feel free to reopen in case you have more questions! :)
