### ISSUE TITLE
with torch.autograd.set_detect_anomaly(True):

### ISSUE THREAD

**Issue by kaka2makaka** [facebookresearch/svoice#17]
https://github.com/facebookresearch/svoice/blob/89d1a1ea44325775ba26a7fc99f3c97a9f0be8e4/svoice/solver.py#L204

Hello!

Why don't you remove this line if code is already debugged.

Thanks!

**Comment by adiyoss** [comment]
Hi @kaka2makaka, 
I agree that you can remove this line of code in case are not interested in debugging, it will probably make training process faster.  
We left it there so others could debug their models using their own created datasets.
