### ISSUE TITLE
Any way in which we can pass our own audio file (mix) ones and get the output in a simplified way? 

### ISSUE THREAD

**Issue by aniketmaithani** [facebookresearch/svoice#2]
- CLI implementation or otherwise to point to one's mix recordings folder in a system 
-  Output the output resultant of mix recording into individual recording 
- Installed the setup but README.md is confusing for me.. and I am not sure how to do the above mentioned thing using this library.

**Comment by adiyoss** [comment]
Hi @aniketmaithani,
You can separate your own mix recordings using:
`python -m svoice.separate --model_path=<path to the model> --mix_dir=<path to the dir with the mixture files> --out_dir=<path to store the separated files>` 
This will go over all the wav files in the `mix_dir` directory, separate them using the model in `model_path`, and output the results to the `out_dir`.
Notice, you should have a trained model. For that, you should train a model using your own data.

**Comment by skwolvie** [comment]
Where is the model stored after following the readme steps?

**Comment by adiyoss** [comment]
should be under: `outputs/exp_`

**Comment by adiyoss** [comment]
Closing this issue for now. If you have any other problems feel free to reopen.
