### ISSUE TITLE
Can't separate using CPU while net trained on GPU

### ISSUE THREAD

**Issue by Gambaryanv** [facebookresearch/svoice#20]
I have trained net with GPU,
I'm truing to separate some files from mix folder:
!python -m svoice.separate /path/to/checkpoint.th /path/to/separated_output --mix_dir=/path/to/mix --device="cpu"

And I have error message:
`RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.`

P.S. I have also tryed different way to point cpu: --device=cpu, --device='cpu'.

**Comment by adiyoss** [comment]
Hi @Gambaryanv,
Can you please pull and try again?

**Comment by adiyoss** [comment]
This issue should be fixed by now. In case you have more questions feel free to reopen! thanks!
