### ISSUE TITLE
How to train on multiple GPUs?

### ISSUE THREAD

**Issue by NNPanNPU** [facebookresearch/svoice#23]

**Comment by adiyoss** [comment]
Hi @NNPanNPU,
Just add `ddp=True` to the running command

**Comment by NNPanNPU** [comment]
> Hi @NNPanNPU,
> Just add `ddp=True` to the running command

Thanks for your reply. How to use specific GPUs?

**Comment by adiyoss** [comment]
Set the `CUDA_VISIBLE_DEVICES` env variable for the gpu ids you would like to use. For example `CUDA_VISIBLE_DEVICES=0,1`

**Comment by adiyoss** [comment]
Closing this issue for now, feel free to reopen in case you have more questions!
