### ISSUE TITLE
What exactly does segment do?

### ISSUE THREAD

**Issue by th3geek** [facebookresearch/svoice#26]
Hi,

I'm curious what exactly does the `segment` variable control? I'm assuming it sets the length of the segment read while training, but how? If it's set to 4 does it only read the _first_ 4 seconds of the file? or does it take a random 4 second portion? If it takes the first 4 seconds, does it then process the next 4 seconds or does it only ever read the first 4 seconds of the file? 

Thanks :)

**Comment by adiyoss** [comment]
So you have two params controlling that. 
1) `segment` which is the processing segment size in seconds (the default is 4 sec)
2) `stride` this one controls the shift of the segments in seconds (the default is 1 sec). 
Meaning that in the default setting the data loader will extract 4 sec segments with shifts of 1 sec for every example. So basically for each example in the dataset you get several training example.

**Comment by adiyoss** [comment]
Closing this for now. Feel free to reopen if you have more questions.
