### ISSUE TITLE
cannot create mix.json (0it [00:00, ?it/s])

### ISSUE THREAD

**Issue by embql** [facebookresearch/svoice#28]
Creating a mix.json doesn't work for me, instead outputting 0it [00:00, ?it/s].

Can you give an example of how the json should look? Then I'll be able to populate it manually.

thanks

**Comment by adiyoss** [comment]
Hi @embql, 
To create the json files you should launch `./make_debug.sh` or use the `audio.py` file.
I uploaded the json files created after launching `make_debug.sh` to the `egs` folder. Notice, the paths are relative at the moment, you should change them to be absolute.

**Comment by embql** [comment]
Thanks, that solved the problem. Running ´./make_debug.sh´ did provide the initial error.

(Now I ran into another system error while accessing the .wav with (I assume) setting torchaudio backend to SoundFile (Windows) being the fix. Will troubleshoot.)

Thanks!
