### ISSUE TITLE
Non-English situation

### ISSUE THREAD

**Issue by hyuan1991** [facebookresearch/svoice#29]
Hi! Thank you for sharing your code.
We plan to use it to separate our mixed-speech in Japanese.
Is it necessary to fine-tune your model in Japanese dataset? and if yes, approximately how many hours of data is needed?

Thank you!

**Comment by adiyoss** [comment]
Hi @hyuan1991,
It is a good question how will the model perform on languages other than english. 
From my experience it is working fine also for other languages (I did not try Japanese though). 
In terms of training-set size, it is hard to say but I believe that ~5-10 hours would be fine. 

Please share updates on your results! :)

**Comment by hyuan1991** [comment]
Thank you for your prompt response!
So, do you mean we can train a model on some English based public dataset (like LibriMix)
and the model trained on English dataset might also work fine on other languages? 

or we have to prepare Japanese dataset for fine-tuning.(there is no such public japanese dataset)

**Comment by adiyoss** [comment]
I would start with training the model on LibriMix and test on other languages. I tested en English based model on French and Hebrew languages and it was working fine. 
Next, I would try to fine-tune on the target language to reach even better performance.

**Comment by hyuan1991** [comment]
Ok! Thank you! 
will share our results once updated!
