### ISSUE TITLE
Can't I customize the location of the outputs folder

### ISSUE THREAD

**Issue by by-XG** [facebookresearch/svoice#30]
Can't I customize the location of the outputs folder？

**Comment by adiyoss** [comment]
Hi @by-XG,
Yes you can! You should change the `hydra.run.dir` argument.
You can either pass it as another argument in the launching command or change it in the config: https://github.com/facebookresearch/svoice/blob/master/conf/config.yaml#L81

**Comment by by-XG** [comment]
> Hi @by-XG,
> Yes you can! You should change the `hydra.run.dir` argument.
> You can either pass it as another argument in the launching command or change it in the config: https://github.com/facebookresearch/svoice/blob/master/conf/config.yaml#L81
Thank you

**Comment by by-XG** [comment]
> 嗨@by-XG，
> 是的，你可以！你应该改变`hydra.run.dir`论点。
> 您可以在启动命令中将其作为另一个参数传递或在配置中更改它：[https](https://github.com/facebookresearch/svoice/blob/master/conf/config.yaml#L81) : [//github.com/facebookresearch/svoice/blob/master/conf/config.yaml#L81](https://github.com/facebookresearch/svoice/blob/master/conf/config.yaml#L81)

**Comment by by-XG** [comment]
Thank you for your prompt response!
