### ISSUE TITLE
Dynamic mixing for training

### ISSUE THREAD

**Issue by Turan111** [facebookresearch/svoice#34]
Why don't you apply dynamic mixing in training? According to recent researches it gives better results.

**Comment by adiyoss** [comment]
@Turan111, 
True it will improve results. However for a fair comparison with previous models in the literature we report results without dynamic mixing. Soon we will upgrade the code with more options (including dynamic mixing).

**Comment by adiyoss** [comment]
I will close this issue as there is not new comments for a while.
Feel free to reopen it if needed.
