### ISSUE TITLE
What is "num_of_scenes, sec, sr"?

### ISSUE THREAD

**Issue by srdfjy** [facebookresearch/svoice#39]
Hi, how do you understand the three parameters of num_of_scenes, sec, and sr in "scripts/make_dataset.py"?

**Comment by adiyoss** [comment]
Hi @srdfjy,
Yes. 
- `num_of_scenes`: the number of different rooms to be simulated. 
- `sec`: the length of each mixture in seconds 
- `sr`: the sampling rate

**Comment by srdfjy** [comment]
thanks @adiyoss
