### ISSUE TITLE
hydra.errors.MissingConfigException: Could not load hydra/hydra_logging/colorlog

### ISSUE THREAD

**Issue by kaka2makaka** [facebookresearch/svoice#4]
Hi!

I am facing this error when running train.py on debug data.

Full error
`(venv_s) noev@pd02-dgx-002:~/svoice$ HYDRA_FULL_ERROR=1 python train.py
Traceback (most recent call last):
  File "train.py", line 126, in <module>
    main()
  File "/home/noev/venv_s/lib/python3.7/site-packages/hydra/main.py", line 37, in decorated_main
    strict=strict,
  File "/home/noev/venv_s/lib/python3.7/site-packages/hydra/_internal/utils.py", line 347, in _run_hydra
    lambda: hydra.run(
  File "/home/noev/venv_s/lib/python3.7/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/home/noev/venv_s/lib/python3.7/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/home/noev/venv_s/lib/python3.7/site-packages/hydra/_internal/utils.py", line 350, in <lambda>
    overrides=args.overrides,
  File "/home/noev/venv_s/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 104, in run
    run_mode=RunMode.RUN,
  File "/home/noev/venv_s/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 512, in compose_config
    from_shell=from_shell,
  File "/home/noev/venv_s/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 156, in load_configuration
    from_shell=from_shell,
  File "/home/noev/venv_s/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 262, in _load_configuration
    run_mode=run_mode,
  File "/home/noev/venv_s/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 804, in _merge_defaults_into_config
    hydra_cfg = merge_defaults_list_into_config(hydra_cfg, system_list)
  File "/home/noev/venv_s/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 783, in merge_defaults_list_into_config
    package_override=default1.package,
  File "/home/noev/venv_s/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 715, in _merge_config
    raise MissingConfigException(msg, new_cfg, options)
hydra.errors.MissingConfigException: Could not load hydra/hydra_logging/colorlog`

How can I solve it?

Thanks!

**Comment by adiyoss** [comment]
Hi @kaka2makaka, 
It seems like a hydra-colorlog plugin issue, did you install the hydra-colorlog properly? 
You can see here: https://hydra.cc/docs/plugins/colorlog/

**Comment by kaka2makaka** [comment]
`(venv_s) noev@pd02-dgx-002:~/svoice$ pip install -r requirements.txt
Looking in indexes: http://mirror.sigma.sbrf.ru/pypi/simple, http://tkle-mess0058.vm.esrt.cloud.sbrf.ru:9090/simple
Requirement already satisfied: pesq==0.0.1 in /home/noev/venv_s/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (0.0.1)
Requirement already satisfied: numpy==1.19.4 in /home/noev/venv_s/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (1.19.4)
Requirement already satisfied: tqdm==4.51.0 in /home/noev/venv_s/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (4.51.0)
Requirement already satisfied: hydra_core==1.0.3 in /home/noev/venv_s/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (1.0.3)
Requirement already satisfied: hydra_colorlog==1.0.0 in /home/noev/venv_s/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (1.0.0)
Requirement already satisfied: pystoi==0.3.3 in /home/noev/venv_s/lib/python3.7/site-packages (from -r requirements.txt (line 6)) (0.3.3)
Requirement already satisfied: torchaudio==0.6.0 in /home/noev/venv_s/lib/python3.7/site-packages (from -r requirements.txt (line 7)) (0.6.0)
Requirement already satisfied: librosa==0.7.1 in /home/noev/venv_s/lib/python3.7/site-packages (from -r requirements.txt (line 8)) (0.7.1)
Requirement already satisfied: numba==0.48 in /home/noev/venv_s/lib/python3.7/site-packages (from -r requirements.txt (line 9)) (0.48.0)
Requirement already satisfied: colorlog in /home/noev/venv_s/lib/python3.7/site-packages (from hydra_colorlog==1.0.0->-r requirements.txt (line 5)) (4.6.2)
Requirement already satisfied: importlib-resources in /home/noev/venv_s/lib/python3.7/site-packages (from hydra_core==1.0.3->-r requirements.txt (line 4)) (1.0.2)
Requirement already satisfied: antlr4-python3-runtime==4.8 in /home/noev/venv_s/lib/python3.7/site-packages (from hydra_core==1.0.3->-r requirements.txt (line 4)) (4.8)
Requirement already satisfied: omegaconf>=2.0.2 in /home/noev/venv_s/lib/python3.7/site-packages (from hydra_core==1.0.3->-r requirements.txt (line 4)) (2.1.0.dev14)
Requirement already satisfied: decorator>=3.0.0 in /home/noev/venv_s/lib/python3.7/site-packages (from librosa==0.7.1->-r requirements.txt (line 8)) (4.4.2)
Requirement already satisfied: joblib>=0.12 in /home/noev/venv_s/lib/python3.7/site-packages (from librosa==0.7.1->-r requirements.txt (line 8)) (1.0.0)
Requirement already satisfied: scikit-learn!=0.19.0,>=0.14.0 in /home/noev/venv_s/lib/python3.7/site-packages (from librosa==0.7.1->-r requirements.txt (line 8)) (0.24.0)
Requirement already satisfied: resampy>=0.2.2 in /home/noev/venv_s/lib/python3.7/site-packages (from librosa==0.7.1->-r requirements.txt (line 8)) (0.2.2)
Requirement already satisfied: scipy>=1.0.0 in /home/noev/venv_s/lib/python3.7/site-packages (from librosa==0.7.1->-r requirements.txt (line 8)) (1.5.4)
Requirement already satisfied: audioread>=2.0.0 in /home/noev/venv_s/lib/python3.7/site-packages (from librosa==0.7.1->-r requirements.txt (line 8)) (2.1.9)
Requirement already satisfied: six>=1.3 in /home/noev/venv_s/lib/python3.7/site-packages (from librosa==0.7.1->-r requirements.txt (line 8)) (1.15.0)
Requirement already satisfied: soundfile>=0.9.0 in /home/noev/venv_s/lib/python3.7/site-packages (from librosa==0.7.1->-r requirements.txt (line 8)) (0.10.3.post1)
Requirement already satisfied: setuptools in /home/noev/venv_s/lib/python3.7/site-packages (from numba==0.48->-r requirements.txt (line 9)) (51.1.0.post20201221)
Requirement already satisfied: llvmlite<0.32.0,>=0.31.0dev0 in /home/noev/venv_s/lib/python3.7/site-packages (from numba==0.48->-r requirements.txt (line 9)) (0.31.0)
Requirement already satisfied: torch==1.6.0 in /home/noev/venv_s/lib/python3.7/site-packages (from torchaudio==0.6.0->-r requirements.txt (line 7)) (1.6.0)
Requirement already satisfied: future in /home/noev/venv_s/lib/python3.7/site-packages (from torch==1.6.0->torchaudio==0.6.0->-r requirements.txt (line 7)) (0.18.2)
Requirement already satisfied: typing-extensions in /home/noev/venv_s/lib/python3.7/site-packages (from omegaconf>=2.0.2->hydra_core==1.0.3->-r requirements.txt (line 4)) (3.7.4.3)
Requirement already satisfied: PyYAML>=5.1.* in /home/noev/venv_s/lib/python3.7/site-packages (from omegaconf>=2.0.2->hydra_core==1.0.3->-r requirements.txt (line 4)) (5.3.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/noev/venv_s/lib/python3.7/site-packages (from scikit-learn!=0.19.0,>=0.14.0->librosa==0.7.1->-r requirements.txt (line 8)) (2.1.0)
Requirement already satisfied: cffi>=1.0 in /home/noev/venv_s/lib/python3.7/site-packages (from soundfile>=0.9.0->librosa==0.7.1->-r requirements.txt (line 8)) (1.14.4)
Requirement already satisfied: pycparser in /home/noev/venv_s/lib/python3.7/site-packages (from cffi>=1.0->soundfile>=0.9.0->librosa==0.7.1->-r requirements.txt (line 8)) (2.20)`
 I got all requirements but it seems like hydra does not see color log package :(

**Comment by adiyoss** [comment]
That is strange...are you using python 3.7?

**Comment by kaka2makaka** [comment]
yes, in venv

**Comment by omry** [comment]
can you provide minimal repro instructions for your problem?
(including the environment setup)

**Comment by kaka2makaka** [comment]
I installed requirements using .whl files, maybe its the problem

**Comment by kaka2makaka** [comment]
```
pip freeze
antlr4-python3-runtime==4.8
audioread==2.1.9
cffi==1.14.4
colorlog==4.6.2
Cython==0.29.21
decorator==4.4.2
future==0.18.2
hydra-colorlog @ file:///home/noev/hydra_colorlog-1.0.0-py3-none-any.whl
hydra-core==1.0.3
importlib-resources==1.0.2
joblib==1.0.0
librosa==0.7.1
llvmlite==0.31.0
numba==0.48.0
numpy==1.19.4
omegaconf==2.1.0.dev14
pesq @ file:///home/noev/packs/pesq-0.0.1
Pillow==8.0.1
pkg-resources==0.0.0
pycparser==2.20
pystoi @ file:///home/noev/packs/pystoi-0.3.3
PyYAML==5.3.1
resampy==0.2.2
scikit-learn==0.24.0
scipy==1.5.4
six==1.15.0
SoundFile==0.10.3.post1
threadpoolctl==2.1.0
torch==1.6.0
torchaudio @ file:///home/noev/packs/torchaudio-0.6.0-cp37-cp37m-manylinux1_x86_64.whl
torchvision==0.7.0
tqdm @ file:///home/noev/packs/tqdm-4.51.0-py2.py3-none-any.whl
typing-extensions==3.7.4.3
```

**Comment by omry** [comment]
Try to re-create the environment from scratch.
If it still happens provide precise instructions to re-create your environment.

Side note:
1. Please upgrade hydra-core 1.0.5.
2. Please do not mix OmegaConf 2.1 with Hydra 1.0 (they are not tested together and are not guaranteed to be compatible).

**Comment by kaka2makaka** [comment]
OK, solved with just removing some colorlog related from config
