### ISSUE TITLE
make_dataset：IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

### ISSUE THREAD

**Issue by srdfjy** [facebookresearch/svoice#40]
Hi，when I used "https://www.openslr.org/28/(RIRS_NOISES/pointsource_noises)" and my own audio file to generate the data set, the following error occurred. But when I change the noise to "wham_noise/tr", it can be successful, how can I solve it?

------------------------------------------------------------

0%|                                                                                                                                                                                       | 0/10 [00:45<?, ?it/s]
Traceback (most recent call last):
  File "scripts/make_dataset.py", line 221, in <module>
    main(args)
  File "scripts/make_dataset.py", line 206, in main
    Data.gen_scene(args.num_of_speakers, i, args.out_path)
  File "scripts/make_dataset.py", line 171, in gen_scene
    noise = self.fetch_noise()
  File "scripts/make_dataset.py", line 151, in fetch_noise
    return s[0:self.size_of_signals, 0]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

**Comment by adiyoss** [comment]
Hi @srdfjy,
Thanks for posting this issue! there was a small bug in the data loading. 
Can you please pull and retry? it should be fine now.

**Comment by srdfjy** [comment]
It's ok now, thanks @adiyoss
