### ISSUE TITLE
Why is the snr range of mixed audio selected from 0-15?

### ISSUE THREAD

**Issue by srdfjy** [facebookresearch/svoice#48]
Hi，When the wsj0 data set mixes audio, the snr range selected is 0-5dB. In "scripts/make_dataset.py", the snr range of mixed audio is 0-15dB. What does this choice have to do with?

**Comment by adiyoss** [comment]
Hi @srdfjy,
The `make_dataset.py` script is used to generate the noisy-reverberant dataset from this paper: https://arxiv.org/pdf/2011.02329.pdf

**Comment by srdfjy** [comment]
Using svoice, if I generate a noise-free data set by myself, without using the "make_dataset.py" script, should I also use the snr range of 0-15dB when mixing audio?

**Comment by adiyoss** [comment]
Hi @srdfjy,
You can mix between the speakers in the range of 0-15dB. But it is up to you, the model does not have any assumption on the dataset generation process.

**Comment by srdfjy** [comment]
thanks @adiyoss
