### ISSUE TITLE
Scale-Invariant Source-to-Distortion Ratio (SI-SDR) 

### ISSUE THREAD

**Issue by walidsst** [facebookresearch/svoice#52]
I think the equation should be like follow, if I'm wrong please correct me.

<a href="https://www.codecogs.com/eqnedit.php?latex=\dpi{300}&space;\bg_white&space;SI-SNR(s_{i},&space;\hat{s}_{i})&space;=&space;10&space;log_{10}(\frac{\left&space;\|&space;\tilde{s}_{i}&space;\right&space;\|^{2}}{\left&space;\|&space;\tilde{e}_{i}&space;\right&space;\|^{2}})" target="_blank"><img src="https://latex.codecogs.com/png.latex?\dpi{300}&space;\bg_white&space;SI-SNR(s_{i},&space;\hat{s}_{i})&space;=&space;10&space;log_{10}(\frac{\left&space;\|&space;\tilde{s}_{i}&space;\right&space;\|^{2}}{\left&space;\|&space;\tilde{e}_{i}&space;\right&space;\|^{2}})" title="SI-SNR(s_{i}, \hat{s}_{i}) = 10 log_{10}(\frac{\left \| \tilde{s}_{i} \right \|^{2}}{\left \| \tilde{e}_{i} \right \|^{2}})" /></a>

**Comment by adiyoss** [comment]
Hi @walidsst,
It depends on what \tilde{s} and \tilde{e} are. Assuming you took it from our paper, than yes :)

**Comment by walidsst** [comment]
yeah I had take it from your paper, because as you define;
<a href="https://www.codecogs.com/eqnedit.php?latex=\dpi{100}&space;\bg_white&space;s&space;=&space;(s_{1},&space;...,&space;s_{i},&space;...,&space;s_{C})" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\dpi{100}&space;\bg_white&space;s&space;=&space;(s_{1},&space;...,&space;s_{i},&space;...,&space;s_{C})" title="s = (s_{1}, ..., s_{i}, ..., s_{C})" /></a> and  <a href="https://www.codecogs.com/eqnedit.php?latex=\dpi{100}&space;\bg_white&space;\hat{s}&space;=&space;(\hat{s}_{1},&space;...,&space;\hat{s}_{i},&space;...,&space;\hat{s}_{C})" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\dpi{100}&space;\bg_white&space;\hat{s}&space;=&space;(\hat{s}_{1},&space;...,&space;\hat{s}_{i},&space;...,&space;\hat{s}_{C})" title="\hat{s} = (\hat{s}_{1}, ..., \hat{s}_{i}, ..., \hat{s}_{C})" /></a> 
also because 
 

<a href="https://www.codecogs.com/eqnedit.php?latex=\dpi{100}&space;\bg_white&space;\tilde{s}_{i}=\frac{<s_{i},\hat{s}_{i}>s_{i}&space;}{\left&space;\|&space;s_{i}&space;\right&space;\|}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\dpi{100}&space;\bg_white&space;\tilde{s}_{i}=\frac{<s_{i},\hat{s}_{i}>s_{i}&space;}{\left&space;\|&space;s_{i}&space;\right&space;\|}" title="\tilde{s}_{i}=\frac{<s_{i},\hat{s}_{i}>s_{i} }{\left \| s_{i} \right \|}" /></a>

I think the equation should be:
<a href="https://www.codecogs.com/eqnedit.php?latex=\dpi{100}&space;\bg_white&space;\text{SI-SNR}(s_{i},&space;\hat{s}_{i})=10log_{10}\frac{\left&space;\|&space;\tilde{s}&space;\right&space;\|}{\left&space;\|&space;\tilde{e}&space;\right&space;\|}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\dpi{100}&space;\bg_white&space;\text{SI-SNR}(s_{i},&space;\hat{s}_{i})=10log_{10}\frac{\left&space;\|&space;\tilde{s}&space;\right&space;\|}{\left&space;\|&space;\tilde{e}&space;\right&space;\|}" title="\text{SI-SNR}(s_{i}, \hat{s}_{i})=10log_{10}\frac{\left \| \tilde{s} \right \|}{\left \| \tilde{e} \right \|}" /></a>

**Comment by walidsst** [comment]
another think here you haven't define the following notation  <a href="https://www.codecogs.com/eqnedit.php?latex=\dpi{100}&space;\bg_white&space;<s_{i},\hat{s}_{i}>" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\dpi{100}&space;\bg_white&space;<s_{i},\hat{s}_{i}>" title="<s_{i},\hat{s}_{i}>" /></a>

correct me if I'm wrong:
<a href="https://www.codecogs.com/eqnedit.php?latex=\dpi{150}&space;\bg_white&space;.&space;\\<s_{i},\hat{s}_{i}>&space;=&space;\sum_{t=0}^{T}&space;s_{i}(t)&space;.&space;\overline{\hat{s}_{i}}(t)&space;\\&space;\text{&space;where&space;}&space;T&space;\text{&space;is&space;the&space;length&space;of&space;}&space;s_{i}/\hat{s}_{i}&space;\\&space;\text{&space;and&space;}&space;\overline{\hat{s}_{i}}&space;\text{&space;is&space;the&space;conjugate&space;of&space;}&space;\hat{s}_{i}&space;\\&space;." target="_blank"><img src="https://latex.codecogs.com/gif.latex?\dpi{150}&space;\bg_white&space;.&space;\\<s_{i},\hat{s}_{i}>&space;=&space;\sum_{t=0}^{T}&space;s_{i}(t)&space;.&space;\overline{\hat{s}_{i}}(t)&space;\\&space;\text{&space;where&space;}&space;T&space;\text{&space;is&space;the&space;length&space;of&space;}&space;s_{i}/\hat{s}_{i}&space;\\&space;\text{&space;and&space;}&space;\overline{\hat{s}_{i}}&space;\text{&space;is&space;the&space;conjugate&space;of&space;}&space;\hat{s}_{i}&space;\\&space;." title=". \\<s_{i},\hat{s}_{i}> = \sum_{t=0}^{T} s_{i}(t) . \overline{\hat{s}_{i}}(t) \\ \text{ where } T \text{ is the length of } s_{i}/\hat{s}_{i} \\ \text{ and } \overline{\hat{s}_{i}} \text{ is the conjugate of } \hat{s}_{i} \\ ." /></a>
