### ISSUE TITLE
AssertionError when training for 3 speakers

### ISSUE THREAD

**Issue by umerjamil16** [facebookresearch/svoice#54]
Hello,

I am training model on Librimix 3 speakers dataset. I've also modified the make_debug.sh file for generating .json file in svoice/egs/debug/tr/ directory. However I am facing error as shown in below code (The model train perfectly for dataset of 2 speakers). 

Would be greatful if someone can point me in a direction towards addressing the issue. 

<pre>[<font color="#06989A">2021-11-15 13:55:47,256</font>][<font color="#3465A4">__main__</font>][<font color="#CC0000">ERROR</font>] - Some error happened
Traceback (most recent call last):
  File &quot;train.py&quot;, line 118, in main
    _main(args)
  File &quot;train.py&quot;, line 112, in _main
    run(args)
  File &quot;train.py&quot;, line 93, in run
    solver.train()
  File &quot;/workspace/svoice/svoice/solver.py&quot;, line 122, in train
    train_loss = self._run_one_epoch(epoch)
  File &quot;/workspace/svoice/svoice/solver.py&quot;, line 210, in _run_one_epoch
    sources, est_src, lengths)
  File &quot;/workspace/svoice/svoice/models/sisnr_loss.py&quot;, line 23, in cal_loss
    source_lengths)
  File &quot;/workspace/svoice/svoice/models/sisnr_loss.py&quot;, line 39, in cal_si_snr_with_pit
    assert source.size() == estimate_source.size()
AssertionError
</pre>

**Comment by adiyoss** [comment]
Hi @umerjamil16,
Did you set `svoice.C=3`? you should specify to how many channels you want to separate the input mixture.

**Comment by umerjamil16** [comment]
Got it, its working fine now. Thanks for the quick reply.

**Comment by Muhammad-Ahmad-Ghani** [comment]
> Got it, its working fine now. Thanks for the quick reply.

@umerjamil16 I need to know where to set the svoice.C value ?

**Comment by qalabeabbas49** [comment]
@umerjamil16 can you share how did the training with librimix go ? with 3 speakers.

I trying to do the same. 

Also, I would appreciate if you could share the config.yaml for 3speakers(librimix).


Thanks
