### ISSUE TITLE
Training for 10 speakers

### ISSUE THREAD

**Issue by muhammad-ahmed-ghani** [facebookresearch/svoice#63]
Hi @adiyoss, can we use this model to train for 10 mixtures ? I have tried but it is giving me assertion error.

    assert source.size() == estimate_source.size()

I have also changed the swave.C value for number of speakers.

**Comment by muhammad-ahmed-ghani** [comment]
@adiyoss Any idea how to resolve this ?

**Comment by adiyoss** [comment]
Hi @Muhammad-Ahmad-Ghani,
It seems there is a mismatch between the input and output dimensions.
If you set `swave.C=10` it will generate 10 different channels. So in that case did you check the dimension of the source signals? maybe you did not load all the data for supervision? can you please check that?

**Comment by muhammad-ahmed-ghani** [comment]
@adiyoss Yeah I have created dataset for 3, 5 and 10 mixtures. Dimensions are correct and the model is working for 3 and 5 mixed signals but it shows error for 10 mixed signals. Don't know why

**Comment by mirosakr** [comment]
Salam Alicom @muhammad-ahmed-ghani  could you please tell me how to check the dimension of the source signals?
I have almost same error.

**Comment by muhammad-ahmed-ghani** [comment]
WaAlaikum Asalam @mirosakr Error is due to files search expression.

Replace the code here in svoice/data/data.py at line 35

<h2>From</h2>

re.compile(r's[0-9].json')


<h2>To</h2>

re.compile(r's[0-9]+.json')

**Comment by mirosakr** [comment]
@muhammad-ahmed-ghani Thanks for your reply
I did as u told me .. but I got this error

  File "/kaggle/working/svoice/svoice/data/audio.py", line 78, in __getitem__
    num_frames=num_frames)[0]
  File "/opt/conda/lib/python3.7/site-packages/torchaudio/backend/sox_backend.py", line 56, in load
    filetype
RuntimeError: Offset past EOF

Any help would be appreciated.

**Comment by muhammad-ahmed-ghani** [comment]
> @muhammad-ahmed-ghani Thanks for your reply I did as u told me .. but I got this error
> 
> File "/kaggle/working/svoice/svoice/data/audio.py", line 78, in **getitem** num_frames=num_frames)[0] File "/opt/conda/lib/python3.7/site-packages/torchaudio/backend/sox_backend.py", line 56, in load filetype RuntimeError: Offset past EOF
> 
> Any help would be appreciated.

Have you changed the C: NUM_SPEAKERS i.e 10 in my case in conf/config.yaml at line 66?

**Comment by mirosakr** [comment]
> 

yes I changed it

**Comment by muhammad-ahmed-ghani** [comment]
> > 
> 
> yes I changed it

Are you using the same dependencies version mentioned in the README ? If yes than I have to look into it because when I trained it I just changed few things due to my dataset and everything worked fine.

**Comment by mirosakr** [comment]
yes, I used the same dependencies version mentioned in the README .. what do u want me to send? and I'll do

I tried to change torchaudio version (torchaudio instead of torchaudi0==0.6.0)
I got another error:

File "/opt/conda/lib/python3.7/site-packages/torch/nn/functional.py", line 4364, in _pad
    return _VF.constant_pad_nd(input, pad, value)
RuntimeError: start (0) + length (-1) exceeds dimension size (56000).

**Comment by muhammad-ahmed-ghani** [comment]
@mirosakr Sorry I haven't replied you back then I was busy with some other stuff. If you still are working on your project and facing issue you can follow this repository [svoice_demo](https://github.com/muhammad-ahmed-ghani/svoice_demo).
It is based on new pytorch version.
