### ISSUE TITLE
RuntimeError: stack expects each tensor to be equal size

### ISSUE THREAD

**Issue by mirosakr** [facebookresearch/svoice#72]
I got an error during validation process
RuntimeError: stack expects each tensor to be equal size, but got [56000] at entry 0 and [27411] at entry 3
Any help would be appreciated.

**Comment by fabianoluzbr** [comment]
@mirosakr I have the same problem. 
you found a solution ?

**Comment by mirosakr** [comment]
> @mirosakr I have the same problem. you found a solution ?

I checked the json file and found that one Id is different in s1 than s2 and mix (they weren't same time) when I updated them to be same time (for s1,s2&mix)
the error solved

**Comment by fabianoluzbr** [comment]
Exactly, thank you!
