### ISSUE TITLE
make_dataset.py is slow to generate samples

### ISSUE THREAD

**Issue by srdfjy** [facebookresearch/svoice#74]
Hi @adiyoss, I used make_dataset.py to generate custom samples, and I also switched to pyrirgen, but it is still very slow (one is generated every second on average), and adding multiple threads has no effect. Is there any way to speed up the generation of samples?

**Comment by adiyoss** [comment]
Hi @srdfjy,
Unfortunately no. You can parallelize this code manually, but we do not have any support for it at the moment.

**Comment by srdfjy** [comment]
@adiyoss thanks!

**Comment by srdfjy** [comment]
make_dataset.py is randomly selected when generating wav, and does not consider repetition, so it may generate repeated audio, which will affect the model effect?
