### ISSUE TITLE
fixed speaker

### ISSUE THREAD

**Issue by srdfjy** [facebookresearch/svoice#75]
Hi @adiyoss ,I want to pin certain speakers to s1 when separating audio, does this model support it?

**Comment by adiyoss** [comment]
The model is invariant to the speakers and speaker order. So we don't have support for it, but it should be straight forward to include it and train the model that like that. You would probably need to change the objective function for that.

**Comment by srdfjy** [comment]
If the number of speakers of the audio to be separated is unknown, select 5 speakers to generate the training sample, and modify config.yaml->swave->C=5. Is the generalization performance of the trained model optimal?
