### ISSUE TITLE
sisnr nan

### ISSUE THREAD

**Issue by srdfjy** [facebookresearch/svoice#76]
Hi, I have the following problem while training 2 or 3 speaker models，generated samples using make_dataset.py, parallelized the generation process, snr(15-30).

This problem does not occur in small samples，what could be the possible reasons for this problem?

--- 
out_sig = out_sig - np.mean(out_sig, axis=1).reshape(B, 1)
2022/06/17 09:52:23 /svoice/svoice/evaluate.py:135: RuntimeWarning: invalid value encountered in subtract
Summary | Epoch 1 | Train 7.01209 | Valid 10.36696 | Best 10.36696 | Sisnr nan | Pesq 0.00000 | Stoi 0.00000

**Comment by srdfjy** [comment]
Hi @adiyoss ，What could be the possible cause of this problem?

If the created samples are all 4 seconds long and the separated wav is greater than 4 seconds, will it matter?

**Comment by Abhishek577** [comment]
hi @srdfjy Is this problem solved..What is the possible soltuion

**Comment by srdfjy** [comment]
> hi @srdfjy Is this problem solved..What is the possible soltuion

Not resolved, I haven't used this for a long time.
