### ISSUE TITLE
Invalid argument: num_frames must be -1 or greater than 0.

### ISSUE THREAD

**Issue by Feavore** [facebookresearch/svoice#95]
i got this issue on training process

**Comment by Feavore** [comment]
i got this issue on training process

**Comment by TokiFeng1** [comment]
how did you fix it?

**Comment by Feavore** [comment]
Hi @TokiFeng1 
In my case, i set wrong path to the [dset](https://github.com/facebookresearch/svoice/blob/main/conf/dset/debug.yaml) config then catched this error.
You should check whether the folder paths in config were correct or json files in that folder were not empty.

**Comment by mynameiswqq** [comment]
sorry,i can not understand your means,please more details,ok?
